### ISSUE TITLE
Compatibility with Bootstrap 4?

### ISSUE THREAD

**Issue by ghost** [smartinsightsfromdata/rpivotTable#116]
The little arrow icons near the rpivotTable's grouping categories, that open the dropdown selection lists, do not work when using [bslib](https://rstudio.github.io/bslib/)'s bootstrap 4 themes in rmarkdown.

However, there is no problem with the aggregators or renderers dropdown arrows.

NOT working with this yaml

```
---
output:
  html_document:
    theme:
      version: 4
      bootswatch: minty
---
```
